---
apiVersion: v1
kind: Service
metadata:
  name: test-app-secretless
  labels:
    app: test-app-secretless
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: test-app-secretless
  type: LoadBalancer

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: conjur-oss

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: test-app-secretless
  labels:
    app: test-app-secretless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app-secretless
  template:
    metadata:
      labels:
        app: test-app-secretless
    spec:
      serviceAccountName: conjur-oss
      containers:
      - image: cyberark/demo-app
        imagePullPolicy: IfNotPresent
        name: test-app-secretless
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /pets
            port: http
          initialDelaySeconds: 15
          timeoutSeconds: 5
        env:
          - name: DB_URL
            value: postgresql://localhost:5432/conjur-oss
      - name: secretless
        image: cyberark/secretless-broker:latest
        imagePullPolicy: Always
        args: ["-f", "/etc/secretless/secretless.yml"]
        ports:
        - name: pg
          containerPort: 5432
        env:
          - name: CONJUR_ACCOUNT
            value: default
          - name: CONJUR_APPLIANCE_URL
            value: "https://conjur.demo.com/api"
          - name: CONJUR_AUTHN_URL
            value: "https://conjur.demo.com/api/authn-k8s/dev"
          - name: CONJUR_AUTHN_LOGIN
            value: "host/conjur/authn-k8s/dev/apps/orquestador/service_account/conjur-oss"
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                key: ssl-certificate
                name: conjur-cert
        volumeMounts:
          - mountPath: /etc/secretless
            name: config
            readOnly: true
      volumes:
        - name: config
          configMap:
            name: secretless-config
            defaultMode: 420
